# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'node.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NodeDialog(object):
    def setupUi(self, NodeDialog):
        NodeDialog.setObjectName("NodeDialog")
        NodeDialog.resize(525, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(NodeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblIPADDR = QtWidgets.QLabel(NodeDialog)
        self.lblIPADDR.setObjectName("lblIPADDR")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblIPADDR)
        self.editIPADDR = QtWidgets.QLineEdit(NodeDialog)
        self.editIPADDR.setObjectName("editIPADDR")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editIPADDR)
        self.lblUsername = QtWidgets.QLabel(NodeDialog)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblUsername)
        self.editUsername = QtWidgets.QLineEdit(NodeDialog)
        self.editUsername.setObjectName("editUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editUsername)
        self.lblpassword = QtWidgets.QLabel(NodeDialog)
        self.lblpassword.setObjectName("lblpassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblpassword)
        self.editPassword = QtWidgets.QLineEdit(NodeDialog)
        self.editPassword.setObjectName("editPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editPassword)
        self.lblScannerAddressLabel = QtWidgets.QLabel(NodeDialog)
        self.lblScannerAddressLabel.setObjectName("lblScannerAddressLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblScannerAddressLabel)
        self.editScannerAddress = QtWidgets.QLineEdit(NodeDialog)
        self.editScannerAddress.setObjectName("editScannerAddress")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editScannerAddress)
        self.lblSSHKey = QtWidgets.QLabel(NodeDialog)
        self.lblSSHKey.setObjectName("lblSSHKey")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblSSHKey)
        self.editSSHKeyFile = QtWidgets.QLineEdit(NodeDialog)
        self.editSSHKeyFile.setEnabled(False)
        self.editSSHKeyFile.setObjectName("editSSHKeyFile")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.editSSHKeyFile)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSSHKey = QtWidgets.QPushButton(NodeDialog)
        self.btnSSHKey.setObjectName("btnSSHKey")
        self.horizontalLayout.addWidget(self.btnSSHKey)
        self.btnTest = QtWidgets.QPushButton(NodeDialog)
        self.btnTest.setObjectName("btnTest")
        self.horizontalLayout.addWidget(self.btnTest)
        self.lblTest = QtWidgets.QLabel(NodeDialog)
        self.lblTest.setObjectName("lblTest")
        self.horizontalLayout.addWidget(self.lblTest)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSave = QtWidgets.QPushButton(NodeDialog)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NodeDialog)
        self.btnTest.clicked.connect(NodeDialog.testConnection)
        self.btnSave.clicked.connect(NodeDialog.saveNode)
        self.btnSSHKey.clicked.connect(NodeDialog.sshkey)
        QtCore.QMetaObject.connectSlotsByName(NodeDialog)

    def retranslateUi(self, NodeDialog):
        _translate = QtCore.QCoreApplication.translate
        NodeDialog.setWindowTitle(_translate("NodeDialog", "Dialog"))
        self.lblIPADDR.setText(_translate("NodeDialog", "Server IP Address"))
        self.lblUsername.setText(_translate("NodeDialog", "User Name"))
        self.lblpassword.setText(_translate("NodeDialog", "Password"))
        self.lblScannerAddressLabel.setText(_translate("NodeDialog", "Scanner Address"))
        self.lblSSHKey.setText(_translate("NodeDialog", "SSH Private Key File"))
        self.btnSSHKey.setText(_translate("NodeDialog", "Select SSH Key  File"))
        self.btnTest.setText(_translate("NodeDialog", "Test Connection"))
        self.lblTest.setText(_translate("NodeDialog", "Status"))
        self.btnSave.setText(_translate("NodeDialog", "Save"))
